### ISSUE TITLE
Issue Import-Module BaselineManagement 

### ISSUE THREAD

**Issue by murasaki718** [microsoft/BaselineManagement#24] opened 2019-02-27 04:33 UTC
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ Import-Module BaselineManagement
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by mgreenegit** [comment] 2020-07-20 23:26
Closing issue. Unable to reproduce error given steps provided.

**Closed by mgreenegit** 2020-07-20 23:26 UTC
